# -*- coding: utf-8 -*-
"""NLP_Training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tHQDDp33kNeoDgDC1iww5Jxmuo1CIy5I

Install Thai *NLP*
"""

!pip install pythainlp

import pythainlp
pythainlp.__version__

pythainlp.thai_characters

pythainlp.thai_letters

!pip install tensorflow deepcut

from pythainlp import sent_tokenize, word_tokenize
text = "สวัสดีครับท่านสมาชิกทุกท่าน"
st = sent_tokenize(text)
print("sent_tokenize: ",st)
print("word_tokenize:",word_tokenize(text))
print("no whitespace:",word_tokenize(text,keep_whitespace = False))

text = "สวัสดีครับท่านสมาชิกทุกท่าน"
print("word_tokenize:",word_tokenize(text))
print("word_tokenize longest:",word_tokenize(text,engine = "longest"))
print("word_tokenize multi_cut:",word_tokenize(text, engine = "multi_cut"))
print("word_tokenize deepcut:",word_tokenize(text, engine = "deepcut"))

from pythainlp.corpus.common import thai_words
from pythainlp.util import Trie
text= "บิตโตะลาเต้คอยน์ช่วงนี้ น่าจะเป็นขาลงนะ วันนี้ฉันว่าจะซื้อเพ่ิม"
print("newmm    :", word_tokenize(text)) 
new_words = {"บิตโตะ","ลาเต้คอยน์"}
words = new_words.union(thai_words())
custom_dictionary_trie = Trie(words)

print(word_tokenize(text,custom_dict=custom_dictionary_trie))

"""Stemming_Lemmatization (English NLP)"""

!pip install nltk

import nltk 
nltk.download()

from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

ps = PorterStemmer()

example_words = ["I","am","going","to","a","party","tonight","She","saw","him","helping","kids"]
example_words2 = ["ran","him","helping","her","kids","saw","shoes","adjustable","feet"]

for w in example_words2:
    print(ps.stem(w))

"""After morning break"""

import nltk 
nltk.download("wordnet")

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

print(lemmatizer.lemmatize('worst', pos="a"))
print(lemmatizer.lemmatize('bestest', pos="a"))
print(lemmatizer.lemmatize('better', pos="a"))

print(lemmatizer.lemmatize('helping', pos="v"))
print(lemmatizer.lemmatize('saw', pos="v"))

print(lemmatizer.lemmatize(' '.join(example_words)))

"""Stopwords jaaaa"""

import nltk 
nltk.download("stopwords")
nltk.download('punkt')

import nltk
from nltk.corpus import stopwords
print(stopwords.words('english'))
print(len(stopwords.words('english')))

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
 
example_txt= "This is a sample sentence, showing off the stop words filtration."
wt = word_tokenize(example_txt)
filtered_sentence = []

for i in wt:
  if i not in stopwords.words('english'):
    filtered_sentence.append(i)

print(filtered_sentence)

from pythainlp.tokenize import word_tokenize
text = "ฉันไม่อยากจะบอกเลยว่าไปห้างทีไร กระเป๋าฉีกทุกที"
list_word = word_tokenize(text)
print(list_word)

from pythainlp.corpus import thai_stopwords
stopwords = list(thai_stopwords())
print(stopwords)
print(len(stopwords))

temp = []
wtt = word_tokenize(text)
for i in wtt:
  if i not in stopwords:
    temp.append(i) 

print(temp)

import pythainlp.word_vector

pythainlp.word_vector.similarity("สุนัข","หมา")

pythainlp.word_vector.similarity("แมว","หมา")

pythainlp.word_vector.doesnt_match({"คน","หมา","เสือ","ข้าว"})

"""Speech to Text """

!pip install SpeechRecognition

import speech_recognition as sr

r = sr.Recognizer()

with sr.AudioFile('record.wav') as source:
  audio_text = r.listen(source)

try:
  text_audio = r.recognize_google(audio_text, language="en")
  print("Starting ...")
  print(text_audio)
except:
  print("Failed")

"""Text to Speech"""

!pip install gTTs

from IPython.display import Audio
from gtts import gTTS

tts = gTTS('อยากเลี้ยงเเมว องค์หญิงน่ารักม๊ากมาก', lang = 'th')
tts.save('speech.mp3')
Audio('speech.mp3', autoplay = True)

tts = gTTS('ちょっとまって (ください) よかった しかたない or しょうがない', lang = 'ja')
tts.save('speech2.mp3')
Audio('speech2.mp3', autoplay = True)

"""Machine Translation (MT)"""

!pip install googletrans==3.1.0a0

from googletrans import Translator
mt = Translator()
translation = mt.translate("Hello what's up boi?", dest = "th")
print(translation.text)

w1 = ["Go go go","I try so hard and got so far","ちょっとまって (ください) よかった しかたない or しょうがない"]
translations = mt.translate(w1 , dest = "th")
for translation in translations:
  print(translation.text)

translator = Translator()
print(translator.detect('ไท'))

"""Exercise: Record the speech -> Translate it and display it via text"""

import speech_recognition as sr
rr = sr.Recognizer()
with sr.AudioFile('record.wav') as source:
  audio_text = rr.listen(source)

try:
  text_audio = r.recognize_google(audio_text, language="en")
  print(text_audio)
  mt = Translator()
  translation = mt.translate(text_audio, dest = "th")
  print(translation.text)
except:
  print("Failed")